main:
	inkscape --export-filename=violin.pdf      violin.svg
	inkscape --export-filename=vlconv1b.pdf 	vlconv1b.svg
	inkscape --export-filename=vlconv1w.pdf 	vlconv1w.svg
	inkscape --export-filename=vlconv2b.pdf 	vlconv2b.svg
	inkscape --export-filename=vlconv2w.pdf 	vlconv2w.svg
	inkscape --export-filename=vlfc1b.pdf 	    vlfc1b.svg
	inkscape --export-filename=vlfc1w.pdf 	    vlfc1w.svg

